### ISSUE TITLE
AID selector UI wireframe

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#10]

**Comment by 2byrds** [comment]
@HunnySajid please provide an updated screen capture for this issue and a link to the figma.

**Comment by HunnySajid** [comment]
### Identifier Attributes

**Alias**: A readable name associated with identifier for an easy reference. This would be used across the app instead the original identifier.

**ID**: Cryptographic alphanumeric string that is a unique ID known as identifier.

**Credentials Received**: This indicates the number of credentials received using this identifier

**Last Used**: A timestamp that indicates last time this identifier has been used to receive / create credentials or logins. 

<img width="1182" alt="Screenshot 2023-12-19 at 9 52 18 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/6d7c3bc3-1686-493e-aff1-2408945fc522">

**Comment by 2byrds** [comment]
Looks great @HunnySajid !
