### ISSUE TITLE
Vendor url UX

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#101]
Optimize for vendor url:
Top priorities:
- Immediately go to the signin page after saving vendor url (good UX)
- Allow a dev to configure (necessary for the community devs)
Lesser priority:
- Allow for themeing from a vendor url, without the agent url (this won't happen often)
- Allow for selection or specifying other agent urls (so that you can switch if needed)

**Comment by 2byrds** [comment]
@HunnySajid will change 'Load' instead of 'Save' for the button for the Vendor url.

**Comment by HunnySajid** [comment]
closing as it is merged with https://github.com/WebOfTrust/signify-browser-extension/pull/105
