### ISSUE TITLE
VC selector UI wireframe

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#11]

**Comment by 2byrds** [comment]
@HunnySajid please provide an updated screen capture for this issue and a link to the figma.

**Comment by HunnySajid** [comment]
### Credential Attributes
Credential metadata is dynamically produced based on the credential schema that is used to create the credential.
<img width="1182" alt="Screenshot 2023-12-19 at 9 52 27 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/f6e93a99-d116-4e55-b8e7-622f5c30b4cf">

For the below-mentioned credential following is the dynamic data:

#### Dynamic Fields
**Stanford**: Name of the issuing institute
**Proof of employment**: Type of the credential
**Name**: Name of the person who is issued this credential
**Date**: Date of Issuance

#### Static Fields
**Education Credential ID**: This is the alias of user's identifier that is used to receive this credential. Note that this same identifier is also listed on identifier screen.
**Issuer ID*: The identifier of issuer. (If we can fetch issuers alias that can be listed here as well)

<img width="1182" alt="Screenshot 2023-12-19 at 9 52 33 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/f9b5938f-c9db-45fd-b237-770f927bb737">


## [Figma Mockups Preview](https://www.figma.com/proto/PRBBiqNRWKhpqXry3XGkjg/Roots-Wallet-Web-Extension?type=design&node-id=160-1058&t=MifpJaw6U2Wfu7KI-0&scaling=min-zoom&page-id=1%3A713&starting-point-node-id=278%3A261&show-proto-sidebar=1)

## [Figma Mockups](https://www.figma.com/file/PRBBiqNRWKhpqXry3XGkjg/Roots-Wallet-Web-Extension?type=design&node-id=1-713&mode=design&t=mIOG92tejvuRDY0W-0)

**Comment by 2byrds** [comment]
Looks great @HunnySajid !
