### ISSUE TITLE
App flow wireframes

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#12]

**Comment by 2byrds** [comment]
@HunnySajid please provide an updated screen capture for this issue and a link to the figma.

**Comment by HunnySajid** [comment]
### App Flow 
App flow is the behavior of KERI extension on a website that requires authentication.

1- Once we land on a website if the extension is not unlocked the alert will ask to open the extension.

<img width="1429" alt="Screenshot 2023-12-20 at 3 38 38 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/fa8ff990-ddf4-4801-a4cf-d3ba220351cc">

<img width="335" alt="Screenshot 2023-12-20 at 3 39 47 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/cb4b1879-2a39-4ed3-8b8d-69513793a800">

2- The user would open up the extension and connect with KERI agent by providing the passcode.

<img width="1426" alt="Screenshot 2023-12-20 at 3 40 46 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/d799237c-9be9-4bb1-b0d5-c4faa2f074b4">

3- After successful login, an alert will be visible showing the website is requesting either an ID or a credential.
It would depend on the website configuration.

**A website requesting an identifier**
<img width="365" alt="Screenshot 2023-12-20 at 3 45 26 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/8fea5eff-f23b-466c-b7e0-33592fc1fbd7">

**A website requesting a credential**
<img width="365" alt="Screenshot 2023-12-20 at 3 45 40 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/0c908d4a-d66b-4b10-b3f9-53a5331b0a45">

4- Once the user clicks on the create button, a list of identifiers or credentials will appear in the alert. User can select any of the items to signin.

**List of identifiers**
<img width="426" alt="Screenshot 2023-12-20 at 3 48 24 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/8c1eaf0f-6072-42cb-850c-914fe3b25f26">

**An identifier is selected to signin**
<img width="426" alt="Screenshot 2023-12-20 at 3 48 38 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/4cfd3ada-1632-49db-89f6-68895e894478">

**List of credentials**
<img width="426" alt="Screenshot 2023-12-20 at 3 49 33 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/eaeb8a43-bc5e-4ca2-9b5b-0c04f32fbb89">

**A credential is selected to signin**
<img width="426" alt="Screenshot 2023-12-20 at 3 49 55 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/d177ecbf-7fa6-4af8-8765-a85aaefaca34">

5- By clicking on the signin user is signed in with that identifier or credential. 
<img width="1432" alt="Screenshot 2023-12-20 at 3 51 25 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/d2f74d07-8d66-4c9f-a51c-a69b8dd91c59">

6- A new entry in login would be created.
<img width="563" alt="Screenshot 2023-12-20 at 3 56 16 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/e98c3460-ed92-4a8c-a54e-aa61724b0869">


7- Next time the alert would show the already existing login to get user autheticated. User can either use the existing login details or can create new ones.

<img width="1432" alt="Screenshot 2023-12-20 at 3 55 31 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/c5235c2e-6994-420d-892a-4ae881b4d478">

**Comment by 2byrds** [comment]
One nit, all references to "Login" should change to "Sign in". Other than that LGTM, thank you!

**Comment by HunnySajid** [comment]
@2byrds All references to Login are replaced with Sign in
