### ISSUE TITLE
Create passcode and boot new agent

### ISSUE THREAD

**Issue by rodolfomiranda** [WebOfTrust/signify-browser-extension#128]
Ability to create a new passcode and boot a new agent

**Comment by rodolfomiranda** [comment]
PR #141 includes two new functions:
- `generatePasscode`
- `bootAndConnect`

I'm attaching an example how the passcode generation and agent creation is implemented in Provenant wallet.

<img width="502" alt="Captura de pantalla 2024-03-16 a las 4 56 02 p m" src="https://github.com/WebOfTrust/signify-browser-extension/assets/2913773/b04c2d4f-dafb-4f2a-b007-a18932fdd268">
<img width="494" alt="Captura de pantalla 2024-03-16 a las 4 56 17 p m" src="https://github.com/WebOfTrust/signify-browser-extension/assets/2913773/d635f9eb-4025-45aa-bbb4-68ae49824dca">

**Comment by HunnySajid** [comment]
Video Link: 
https://www.loom.com/share/74b31b3342e046a4b27e57dd2c6fedaa?sid=c0a212a1-b3d2-4b24-9552-3355c509411a

**Comment by HunnySajid** [comment]
closing as it is merged with https://github.com/WebOfTrust/signify-browser-extension/pull/142
