### ISSUE TITLE
Prompt user to accept configuration from a web page

### ISSUE THREAD

**Issue by rodolfomiranda** [WebOfTrust/signify-browser-extension#130]
As we discussed today, we will change a bit the flow when onboarding:
- the normal popup in a web page will be shown to head the user to click on the action button
- the config page will be shown with vendor URL and a message telling the user to accept or deny it. Also shown that the config came from the web page

**Comment by HunnySajid** [comment]
closing as it is merged with https://github.com/WebOfTrust/signify-browser-extension/pull/133
