### ISSUE TITLE
Remove hardcoded ports and test IP based agents, etc.

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#150]
- [x] Ronak will supply IP based agent
- [x] Remove health check validate
- [x] Add configurable boot url at a different port and adjust front-end depending on the boot url added.

**Comment by HunnySajid** [comment]
Closing as it is merged with https://github.com/WebOfTrust/signify-browser-extension/pull/152

Ronak and I were able to connect his AWS instance with extension.
