### ISSUE TITLE
The extension freezes if it cannot connect to a KERIA server

### ISSUE THREAD

**Issue by nkongsuwan** [WebOfTrust/signify-browser-extension#173]
Currently, if a KERIA server, to which the extension has previously connected, becomes unavailable, then the extension completely freezes without any means for the user to interact with the extension.

I recommend adding a button to force disconnect so that the user can change the KERIA URL and reconnect to another KERIA server.

**Comment by 2byrds** [comment]
@HunnySajid can this be closed now?

**Comment by HunnySajid** [comment]
@2byrds yes
