### ISSUE TITLE
Workflow automation to build/zip creation 

### ISSUE THREAD

**Issue by HunnySajid** [WebOfTrust/signify-browser-extension#193]
Set up github workflow to create dev, rc, or latest build for extension whenever there is a new pr merged. It should also zip the dist along with the version number.

**Comment by 2byrds** [comment]
I suppose we want the new artifacts to be available to devs, where will those live?
Also this should eventually feed the chrome extension catalog @HunnySajid ?

**Comment by HunnySajid** [comment]
> I suppose we want the new artifacts to be available to devs, where will those live? Also this should eventually feed the chrome extension catalog @HunnySajid ?

Yes, it is for devs and it will help us to track changes as versions. 
Where will those live? I have not decided but i am thinking to keep it in a github repository 
Regarding chrome extension catalog upload, that would be the ideal case but is a lot complex. I have not thought about that but will research.
