### ISSUE TITLE
Add setup instructions?

### ISSUE THREAD

**Issue by daidoji** [WebOfTrust/signify-browser-extension#212]
While the extension does build and load the setup instructions in [GETTING_STARTED_VENDOR.md](https://github.com/WebOfTrust/signify-browser-extension/blob/main/GETTING_STARTED_VENDOR.md) and [GETTING_STARTED_WEB_CLI.md](https://github.com/WebOfTrust/signify-browser-extension/blob/main/GETTING_STARTED_WEB_CLI.md) don't quite seem to get us to a workable plugin example.  

Would it be possible to add instructions on a baseline setup for this extension?  We know we need to run a web app, the extension, and a KERIA agent and we think we've figured out where those should go from the diagrams, but beyond that it's unclear how (and what) the bootURL, agentURL, and vendorURL should configure/be configured as in order to get the extension to run.

**Comment by edeykholt** [comment]
@daidoji In the meantime, there is some documentation here:  https://github.com/2byrds/reg-pilot/blob/demo_oct_2024/demo/DEMO.md
