### ISSUE TITLE
Add user name to extension?

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#213]
Currently if two users use the same passcode they will get mapped to the same agent. Phil had suggested to add a user name. Lets discuss and consider adding it to the passcode generation/creation and to the 'login' page in order to avoid this issue.

**Comment by edeykholt** [comment]
Brainstorming, brainstorming...
Other than in testing scenarios, if any two separate users have the same passcode on a KERIA instance, there are other big problems, right?
I suppose with KATE, KERIA can't force good randomness of passcode (seed) generation from well written clients.
Is it a hard goal that beyond the passcode and the KERIA urls, the user/client shouldn't have to know anything else?  Now, the proposal is to add a disambiguating user name and ask the user to provide this always or only on conflict?  Yuck.

How about having KERIA create a guid for a KERIA "account", where the guid would typically not be presented to the user?  But, it could be in the form of a generated icon if needed to choose which account to use? Yuck, too.

In brainstorming for a solution, we should also consider when in the future a KERIA service could be replicated for high availability, so an account guid (plus a weak hash of the passcode?) could be used as an account identifier for synchronizing across those service instances, with those services having some common identifier so it is clear to the clients they are connected to one of their supporting KERIA instances?  (Or the service instances participate in a multisig group, and each have an AID and could prove they are of the same group.)

**Comment by rodolfomiranda** [comment]
AIDs are unique, that's a ground truth in KERI. It's almost impossible to generate the same passcode twice, unless you are using a salt to avoid randomness while testing.
