### ISSUE TITLE
[Bug] When you press "enter" after filling in the Agent URL in the settings it takes you back to the landing page of extension

### ISSUE THREAD

**Issue by daidoji** [WebOfTrust/signify-browser-extension#216]
# To reproduce
1. New extension loaded from a build of main @ 2799a clean no settings.
2. Type in a URL to the agentURL box
3. As soon as you press Enter it takes you back to the landing page of the extension (even though the person probably wants to fill in the settings for the bootURL.

# To resolve
Don't go back to landing page until the user clicks "save".

# build env
Chrome: Version 130.0.6723.92 (Official Build) (64-bit)
Build Extension from main commit: https://github.com/WebOfTrust/signify-browser-extension/commit/2799a162ae1b93bc54c284f1833aa4077e58e876

**Comment by HunnySajid** [comment]
can be closed if https://github.com/WebOfTrust/signify-browser-extension/pull/219 is merged

**Comment by HunnySajid** [comment]
@daidoji can you please provide your feedback and we can close this one if the [changes](https://github.com/WebOfTrust/signify-browser-extension/pull/219) are satsifactory.

**Comment by daidoji** [comment]
@HunnySajid sure, it seems to be fixed now.
