### ISSUE TITLE
Content Script Alerts UI

### ISSUE THREAD

**Issue by HunnySajid** [WebOfTrust/signify-browser-extension#35]

**Comment by 2byrds** [comment]
From our meeting today:
- [ ] Instead of 'Signin' it should be 'Sign in', all over the extension.
- [ ] Instead of alias 'holder' it should be 'Bank Employee'
- [ ] 'Sign in with KERI' alert should show only the AID of the user tied to that webpage
- [ ] 'Sign in with KERI' alert should have 'Select identifier' button if there are multiple sign ins with the page
- [ ] The webpage needs to have a listener for the asynchronous message waiting for the user to do the sign in. @HunnySajid  said it will be listening to 'send message' event. @rodolfomiranda will implement the functionality for the extension/backen, @HunnySajid will update the page to handle that properly.
- [ ] 'Sign in with KERI' has a 'Create' button that should be removed and initiated automatically to the extension
- [ ] 'Sign in with KERI' has a 'Select the KERI icon in your browser to proceed' alert.... 
- [ ] The radio button for selection of Identifiers/Credentials looks odd
- [ ] Once a sign in is selected, it should automatically sign in instead @rodolfomiranda will provide that. And will implement that.

**Comment by HunnySajid** [comment]
> * Instead of 'Signin' it should be 'Sign in', all over the extension.
> * [ ]  Instead of alias 'holder' it should be 'Bank Employee'
> * [ ]  'Sign in with KERI' alert should show only the AID of the user tied to that webpage
> * [ ]  'Sign in with KERI' alert should have 'Select identifier' button if there are multiple sign ins with the page
> * [ ]  The webpage needs to have a listener for the asynchronous message waiting for the user to do the sign in. @HunnySajid  said it will be listening to 'send message' event. @rodolfomiranda will implement the functionality for the extension/backen, @HunnySajid will update the page to handle that properly.
> * [ ]  'Sign in with KERI' has a 'Create' button that should be removed and initiated automatically to the extension
> * [ ]  The radio button for selection of Identifiers/Credentials looks odd
> * [ ]  Once a sign in is selected, it should automatically sign in instead @rodolfomiranda will provide that. And will implement that.

- [x] Instead of 'Signin' it should be 'Sign in', all over the extension.
- [x] 'Sign in with KERI' alert should show only the AID of the user tied to that webpage
- [x] 'Sign in with KERI' alert should have 'Select identifier' button if there are multiple sign ins with the page
- [x] 'Sign in with KERI' has a 'Create' button that should be removed and initiated automatically to the extension

- [ ]  Instead of alias 'holder' it should be 'Bank Employee'
@AlexAndrei98 please update the identifier's name from holder to Bank Employee

@2byrds I am working on some UI changes where the radio button would also be updated.

**Comment by 2byrds** [comment]
> > * Instead of 'Signin' it should be 'Sign in', all over the extension.
> > * [ ]  Instead of alias 'holder' it should be 'Bank Employee'
> > * [ ]  'Sign in with KERI' alert should show only the AID of the user tied to that webpage
> > * [ ]  'Sign in with KERI' alert should have 'Select identifier' button if there are multiple sign ins with the page
> > * [ ]  The webpage needs to have a listener for the asynchronous message waiting for the user to do the sign in. @HunnySajid  said it will be listening to 'send message' event. @rodolfomiranda will implement the functionality for the extension/backen, @HunnySajid will update the page to handle that properly.
> > * [ ]  'Sign in with KERI' has a 'Create' button that should be removed and initiated automatically to the extension
> > * [ ]  The radio button for selection of Identifiers/Credentials looks odd
> > * [ ]  Once a sign in is selected, it should automatically sign in instead @rodolfomiranda will provide that. And will implement that.
> 
> - [x] Instead of 'Signin' it should be 'Sign in', all over the extension.
> - [x] 'Sign in with KERI' alert should show only the AID of the user tied to that webpage
> - [x] 'Sign in with KERI' alert should have 'Select identifier' button if there are multiple sign ins with the page
> - [x] 'Sign in with KERI' has a 'Create' button that should be removed and initiated automatically to the extension
> 
> - [ ]  Instead of alias 'holder' it should be 'Bank Employee'
> @AlexAndrei98 please update the identifier's name from holder to Bank Employee
> 
> @2byrds I am working on some UI changes where the radio button would also be updated. 

Great thx @HunnySajid !

**Comment by 2byrds** [comment]
From our meeting today:
- [ ] The webapp must show what the authentication produces (signed headers should be shown to the user)
- [ ] Holder should be 'Banker'
- [ ] 'Select another credential' should go away in favor of the 'Select the KERI icon in your browser to proceed' message
- [ ] 'Select the KERI icon in your browser to proceed' message should have 'KERI' themeing (KERI green text)
- [ ] Consistent selection lists... meaning no radio button w/ a select button... instead an arrow denoting select, with text behind it for context.... so something like "Select >" or "Sign In >" etc.
- [ ] Tighten the cards size, etc.
- [ ] @rodolfomiranda will merge his PR and @HunnySajid will rebase it etc.

**Comment by 2byrds** [comment]
https://github.com/WebOfTrust/signify-browser-extension/pull/50
