### ISSUE TITLE
Discuss how configuration/settings will work for the white label extension

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#4]
Use Daniels initial design/definition of what the URL for theming will supply and hold a meeting to present the possibilities to the community.

**Comment by rodolfomiranda** [comment]
The following is the description of the requested feature from Provenant's bounty document:
> Configuration with a vendor (Keria provider). Upon install, the extension MUST allow a person to provide a configuration URL for a vendor that will provide the Keria agent for the Signify instance that runs in the extension. Without a vendor who hosts Keria, the extension is not functional.
This URL is NOT the URL of the agent, but rather a URL that MUST be browsable by a person. It should point to an onboarding web page hosted by the vendor, that walks the user through a configuration experience and that ultimately redirects the user to a URL that serves a JSON object with the following configuration parameters:
> - agent_url: where Signify can call the user's Keria agent.
> - vendor_css: URL where the vendor's CSS can rebrand the UI of the extension.
> strings_url: A nullable URL that includes the token "lang=??". This URL returns a JSON object that contains localized strings for the extension; the extension will call this URL, substituting a lang code appropriate to the user's browser settings.
> support_url: A URL where the user can get support from the vendor.
> docs_url: A URL where the user can browse documentation about the extension as supported by that vendor.
> management_url: A URL which allows the vendor to override the basic UI of the extension. It may be null. If it's null, the extension displays a default UI in a popup window, to help users to manage, create, and select identifiers and credentials to authenticate to a web site. If it's NOT null, the extension loads HTML from this URL to perform management tasks.
>
>(Note: need to discuss overall config strategy. There are cybersecurity implications if we get too fancy, but there are problems with overreach in the UI of this extension if we don't give vendors enough freedom.)

**Comment by rodolfomiranda** [comment]
Meeting scheduled on Friday 7:30 EST. Google meet link: https://meet.google.com/koi-ntog-hup

**Comment by dhh1128** [comment]
I think that describing this as "theming" is misdescribing its purpose a little. It is true that we will derive from this feature the ability to theme the extension. However, its more important purposes are:

1. Allow the extension to be configured with policies for its associated agent. (Agents are drastically more powerful than just providers of encrypted storage for dumb wallets, but unless this browser extension has a way to configure said agents, it can't access that power.)

2. Allow the owner of a web (or mobile) wallet to establish a relationship with one or more value-added websites that will deliver powerful features that depend on much more than the simple authentication of an ordinary website, but that require the user and the wallet they control to make accountable choices using their AIDs/keys/credentials.

If we don't give these purposes their proper weight, then we will create feature pressure on the extension. We will be tempted to add more and more sophisticated features to it, so website X and website Y can get more and more sophisticated in their user interactions. But if we think about it properly, then the extension remains simple and pure (a wallet plus a generic, simple authentication mechanism), and all those extra features move into the websites that interact with the wallet. That's where those features belong.

**Comment by rodolfomiranda** [comment]
You are correct Daniel. This is about the configuration of a KERIA provider that should also include an onboarding process to simplify the adoption, as well as the setting the relationship policies to value-added websites.

**Comment by 2byrds** [comment]
From our meeting today:
@rodolfomiranda will update the information in the comments.

**Comment by rodolfomiranda** [comment]
The following is the proposed mechanism to configure the browser extension:

- User will onboard with a KERIA provider and obtain a configuration URL
- after installing the browser extension  will ask for the configuration URL
- the browser extension will use the URL to GET a JSON  with configuration parameters/values
- the browser extension will apply configuration values to personalize the UI such as:
   - logo
   - colors
   - fonts
   - titles
   - labels

Additionally, the browser extension GitHub repository will contain a file with known keria providers URLs that the browser extension will use to facilitate the configuration. The list of keria providers can be updated with a PR approved by the community
