### ISSUE TITLE
Extension UI wireframe

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#6]
This allows you to enter a url to connect to your KERIA agent.
Success should lead you to enter your passcode here https://github.com/WebOfTrust/signify-browser-extension/issues/7
If you haven't onboarded to a KERIA agent before, then you will go through a set of onboarding screens (future work) to setup your passcode and agent, then you will go to the Login/passcode screen.

**Comment by HunnySajid** [comment]
1. Initial screen, The user is asked to connect with KERI agent by providing:

- Keri URL
- Passcode
 
<img width="1182" alt="Screenshot 2023-12-19 at 9 56 27 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/35111489-9c7a-4a04-9a21-e2972eb9bff9">


2. After providing the url and passcode user can click on connect button to proceed.

<img width="1182" alt="Screenshot 2023-12-19 at 9 52 07 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/8f884cf3-e9e2-48cb-ac8c-5b01b55dbb3f">

3. When succeeded, user can visit main extension display that lists the followings:
- Identifiers
- Credentials
- Logins

### Identifier Attributes

**Alias**: A readable name associated with identifier for an easy reference. This would be used across the app instead the original identifier.

**ID**: Cryptographic alphanumeric string that is a unique ID known as identifier.

**Credentials Received**: This indicates the number of credentials received using this identifier

**Last Used**: A timestamp that indicates last time this identifier has been used to receive / create credentials or logins. 

<img width="1182" alt="Screenshot 2023-12-19 at 9 52 18 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/6d7c3bc3-1686-493e-aff1-2408945fc522">

### Credential Attributes
Credential metadata is dynamically produced based on the credential schema that is used to create the credential.
<img width="1182" alt="Screenshot 2023-12-19 at 9 52 27 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/f6e93a99-d116-4e55-b8e7-622f5c30b4cf">

For the below-mentioned credential following is the dynamic data:

#### Dynamic Fields
**Stanford**: Name of the issuing institute
**Proof of employment**: Type of the credential
**Name**: Name of the person who is issued this credential
**Date**: Date of Issuance

#### Static Fields
**Education Credential ID**: This is the alias of user's identifier that is used to receive this credential. Note that this same identifier is also listed on identifier screen.
**Issuer ID*: The identifier of issuer. (If we can fetch issuers alias that can be listed here as well)

<img width="1182" alt="Screenshot 2023-12-19 at 9 52 33 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/f9b5938f-c9db-45fd-b237-770f927bb737">

### Login Attributes

**Website**: The website url to which this login belongs to.
**Username**: Username for the user who is associated with this login.
**Credential** OR **ID Alias**: The login could required either a credential or an identifier. The credential title or ID Alias would be listed here.
**Last Used**: Timestamp that shows last time this login was used to authenticate a website.

<img width="1182" alt="Screenshot 2023-12-19 at 9 52 45 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/d7f7a714-d7e5-40ea-8795-95deadf1863e">


## The mockup preview is [availabe here](https://www.figma.com/proto/PRBBiqNRWKhpqXry3XGkjg/Roots-Wallet-Web-Extension?type=design&node-id=278-261&t=MifpJaw6U2Wfu7KI-0&scaling=min-zoom&page-id=1%3A713&starting-point-node-id=278%3A261)

**Comment by HunnySajid** [comment]
@2byrds All references to Login are replaced with Sign in
