### ISSUE TITLE
Login (w/ passcode) UI wireframe

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#7]

**Comment by HunnySajid** [comment]
**Screen : Login with passphrase** 

<img width="355" alt="Screenshot 2023-12-11 at 5 38 51 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/5d2b6456-9241-4edd-8668-51f7ab993f63">

**Elements**
1- Vendor name (e.g KERI)
2- Settings Icon (Opens settings screen or popup)
3- Vendor Logo (e.g KERI logo)
4- Pass phrase input field
5- Login Button
6- Links to docs and support pages

**Comment by 2byrds** [comment]
@HunnySajid please provide an updated screen capture for this issue and a link to the figma.

**Comment by HunnySajid** [comment]
### Login Screen 
The first time login screen would ask for KERI url and passcode. 
In next iterations when we are required to login (e.g after session expires), it would only ask for passcode.

**First time Login**
<img width="1182" alt="Screenshot 2023-12-19 at 9 56 27 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/e2f63740-5ef9-4d44-8931-1d966530a722">

**Onwards**
<img width="428" alt="Screenshot 2023-12-20 at 3 19 04 AM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/417343d9-436d-42d4-aa5e-30e35469da21">

**Comment by 2byrds** [comment]
Looks great @HunnySajid !
