### ISSUE TITLE
Localisation support

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#82]
We need support for modifying the language support for the extension

**Comment by 2byrds** [comment]
From our meeting today:
To start, localisation per language will be saved in a file within the signify-browser-extension repo so that others can contribute as needed. We will start with english to show the example. Eventually vendors will be able to extend this, but for now we will rely on the browser language selection. @HunnySajid will provide the English localization.

**Comment by HunnySajid** [comment]
https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/a62ea5f0-d046-49d1-93be-17c08ef3494b

**Comment by HunnySajid** [comment]
dropdown has been added and merged in https://github.com/WebOfTrust/signify-browser-extension/pull/86

**Comment by HunnySajid** [comment]
Localisation has be reviewed and merged into main
