### ISSUE TITLE
Demo review changes

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#93]
- [ ] Abbreviated identifiers should have hover over to see the full identifier
- [ ] On identifier creation, if there is a failure, supply an error message
- [ ] Session can be interrupted while the app is running, this needs a fix or clever way to prompt user to reconnect.
- [ ] All screens need a way to notify user if disconnected or some other error.
- [ ] The credential 'Select' button needs more padding
- [ ] The identifier 'Select' button needs more padding
- [ ] Credential 'sign-in' button should not wrap
- [ ] The example webapp should navigate to a welcome screen once sign-in successful. The welcome screen should tell the user what they signed in with and display the errors.

**Comment by HunnySajid** [comment]
> * [x]  Abbreviated identifiers should have hover over to see the full identifier
> * [x]  On identifier creation, if there is a failure, supply an error message
> * [x]  Session can be interrupted while the app is running, this needs a fix or clever way to prompt user to reconnect.
> * [x]  All screens need a way to notify user if disconnected or some other error.
> * [x]  The credential 'Select' button needs more padding
> * [x]  The identifier 'Select' button needs more padding
> * [x]  Credential 'sign-in' button should not wrap
> * [ ]  The example webapp should navigate to a welcome screen once sign-in successful. The welcome screen should tell the user what they signed in with and display the errors.

All except last point are covered in https://github.com/WebOfTrust/signify-browser-extension/pull/92

Separate task for the last point https://github.com/WebOfTrust/signify-browser-extension/issues/94

**Comment by HunnySajid** [comment]
Closing as it is merged with https://github.com/WebOfTrust/signify-browser-extension/pull/92
