### ISSUE TITLE
Proper validation messages from signify-ts

### ISSUE THREAD

**Issue by HunnySajid** [WebOfTrust/signify-browser-extension#95]
I need to check if the agentUrl is correct/active or invalid on config screen.
Is there a way to validate that? 
It should return an error, something like "the agent is not active"

<img width="350" alt="Screenshot 2024-02-15 at 10 19 17 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/b812420a-561f-4c2a-b7a8-e160ef599d1f">

Also if I use a wrong pair of agentUrl + password it gives this long error. It should be more descriptive.

<img width="350" alt="Screenshot 2024-02-15 at 10 21 44 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/56d1f466-b833-433d-9bc2-7ce44651fc46">

For passcode that is not 21 characters long, it shows this error.
Instead of "bran must be 21 characters" it should say "passcode must be 21 characters" or simply "incorrect passcode"

<img width="350" alt="Screenshot 2024-02-15 at 10 25 05 PM" src="https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/1e732bbe-b985-4f3f-bc12-a70d752d895b">

**Comment by HunnySajid** [comment]
To check the validity of agentUrl, GET the agent URL with path /health and receive a message like {"message": f"Health is okay. Time is {nowIso8601()}"}
e.g `https://keria-dev.rootsid.cloud/health`
It may be not opened in our KERIA instance. @rodolfomiranda will check it.

**Comment by rodolfomiranda** [comment]
health API es running now on keri-dev.rootsid.cloud
