### ISSUE TITLE
Host example web app to test in production

### ISSUE THREAD

**Issue by HunnySajid** [WebOfTrust/signify-browser-extension#97]
We need to host example-webapp so that anyone can test the extension in production.

1- host webapp online
2- provide a link to latest distribution of extension

**Comment by HunnySajid** [comment]
Hosted Web App Link ([From forked repo](https://github.com/HunnySajid/signify-browser-extension/tree/main)): https://signify-browser-extension.vercel.app/

Run extension locally
- clone [this repo](https://github.com/WebOfTrust/signify-browser-extension)
- [Follow this link](https://medium.com/@aabroo.jalil/how-to-test-a-chrome-extension-locally-step-by-step-guide-852e4622d4c7) to know how to run extension locally in chrome

**Comment by HunnySajid** [comment]
NOTE: this issue is not closed as the [original repo](https://github.com/WebOfTrust/signify-browser-extension) is not deployed yet.

**Comment by 2byrds** [comment]
It's good enough for all the information to be in the weboftrust repo, but no need to have that repo actually host the vercal app. As long as @HunnySajid fork can provide a stable url that people can try, that could just be linked to the dev guide so that people can try it.

**Comment by HunnySajid** [comment]
closing as https://github.com/WebOfTrust/signify-browser-extension/pull/100 is merged
