### ISSUE TITLE
Health check for Keria agent

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/signify-browser-extension#98]
the /health url for rootsID keria instance is available if we upgrade.
It probably needs to be exposed.

**Comment by rodolfomiranda** [comment]
I exposed the `\health` interface but it's not available in the keria version of the instance that is currently running in rootsid.cloud.  I prefer not to update to latest right now since many changes were applied. We can test in a keria running on localhost.

**Comment by rodolfomiranda** [comment]
this is the response I got with `http://localhost:3903/health`

```{"message": "Health is okay. Time is 2024-02-19T19:36:49.254598+00:00"}```

**Comment by rodolfomiranda** [comment]
Health api is working on https://keria-dev.rootsid.cloud/health
